import os
from dotenv import load_dotenv

# Загружаем переменные окружения из текущего каталога и из intraday-levels-taapi/.env
load_dotenv()
try:
    _here = os.path.dirname(__file__)
    _project_env = os.path.normpath(os.path.join(_here, "..", ".env"))
    if os.path.exists(_project_env):
        load_dotenv(_project_env)
except Exception:
    pass

# Taapi.io API
TAAPI_KEY = os.getenv("TAAPI_KEY")
TAAPI_BASE_URL = "https://api.taapi.io"

# Настройки символов и таймфреймов
SYMBOLS = os.getenv("SYMBOLS", "1000000BOBUSDT,1000000MOGUSDT,1000BONKUSDT,1000CATUSDT,1000CHEEMSUSDT,1000FLOKIUSDT,1000LUNCUSDT,1000PEPEUSDT,1000RATSUSDT,1000SATSUSDT,1000SHIBUSDT,1000WHYUSDT,1000XUSDT,1000XECUSDT,1INCHUSDT,1MBABYDOGEUSDT,AUSDT,A2ZUSDT,AAVEUSDT,ACAUSDT,ACEUSDT,ACHUSDT,ACMUSDT,ACTUSDT,ACXUSDT,ADAUSDT,ADXUSDT,AEROUSDT,AEURUSDT,AEVOUSDT,AGLDUSDT,AGTUSDT,AIUSDT,AI16ZUSDT,AINUSDT,AIOUSDT,AIOTUSDT,AIXBTUSDT,AKTUSDT,ALCHUSDT,ALCXUSDT,ALGOUSDT,ALICEUSDT,ALLUSDT,ALPINEUSDT,ALTUSDT,AMPUSDT,ANIMEUSDT,ANKRUSDT,APEUSDT,API3USDT,APTUSDT,ARUSDT,ARBUSDT,ARCUSDT,ARDRUSDT,ARIAUSDT,ARKUSDT,ARKMUSDT,ARPAUSDT,ASRUSDT,ASTRUSDT,ATAUSDT,ATHUSDT,ATMUSDT,ATOMUSDT,AUCTIONUSDT,AVAUSDT,AVAAIUSDT,AVAXUSDT,AVNTUSDT,AWEUSDT,AXLUSDT,AXSUSDT,BUSDT,B2USDT,B3USDT,BABYUSDT,BAKEUSDT,BANUSDT,BANANAUSDT,BANANAS31USDT,BANDUSDT,BANKUSDT,BARUSDT,BASUSDT,BATUSDT,BBUSDT,BCHUSDT,BDXNUSDT,BEAMXUSDT,BELUSDT,BERAUSDT,BFUSDUSDT,BICOUSDT,BIDUSDT,BIFIUSDT,BIGTIMEUSDT,BIOUSDT,BLURUSDT,BMTUSDT,BNBUSDT,BNSOLUSDT,BNTUSDT,BOMEUSDT,BONKUSDT,BRUSDT,BRETTUSDT,BROCCOLI714USDT,BROCCOLIF3BUSDT,BSVUSDT,BTCUSDT,BTCDOMUSDT,BTRUSDT,BULLAUSDT,CUSDT,C98USDT,CAKEUSDT,CARVUSDT,CATIUSDT,CELOUSDT,CELRUSDT,CETUSUSDT,CFXUSDT,CGPTUSDT,CHESSUSDT,CHILLGUYUSDT,CHRUSDT,CHZUSDT,CITYUSDT,CKBUSDT,COMPUSDT,COOKIEUSDT,COSUSDT,COTIUSDT,COWUSDT,CROSSUSDT,CRVUSDT,CTKUSDT,CTSIUSDT,CUDISUSDT,CYBERUSDT,DUSDT,DAMUSDT,DASHUSDT,DATAUSDT,DCRUSDT,DEEPUSDT,DEGENUSDT,DEGOUSDT,DENTUSDT,DEXEUSDT,DFUSDT,DIAUSDT,DMCUSDT,DODOXUSDT,DOGEUSDT,DOGSUSDT,DOLOUSDT,DOODUSDT,DOTUSDT,DRIFTUSDT,DUSKUSDT,DYDXUSDT,DYMUSDT,EDUUSDT,EGLDUSDT,EIGENUSDT,ENAUSDT,ENJUSDT,ENSUSDT,EPICUSDT,EPTUSDT,ERAUSDT,ESPORTSUSDT,ETCUSDT,ETHUSDT,ETHFIUSDT,ETHWUSDT,EURIUSDT,FUSDT,FARMUSDT,FARTCOINUSDT,FDUSDUSDT,FETUSDT,FHEUSDT,FIDAUSDT,FILUSDT,FIOUSDT,FISUSDT,FLMUSDT,FLOCKUSDT,FLOKIUSDT,FLOWUSDT,FLUXUSDT,FORMUSDT,FORTHUSDT,FUNUSDT,FXSUSDT,GUSDT,GALAUSDT,GASUSDT,GHSTUSDT,GLMUSDT,GMTUSDT,GMXUSDT,GNOUSDT,GNSUSDT,GOATUSDT,GPSUSDT,GRASSUSDT,GRIFFAINUSDT,GRTUSDT,GTCUSDT,GUNUSDT,HUSDT,HAEDALUSDT,HBARUSDT,HEIUSDT,HEMIUSDT,HFTUSDT,HIFIUSDT,HIGHUSDT,HIPPOUSDT,HIVEUSDT,HMSTRUSDT,HOLOUSDT,HOMEUSDT,HOOKUSDT,HOTUSDT,HUMAUSDT,HYPEUSDT,HYPERUSDT,ICNTUSDT,ICPUSDT,ICXUSDT,IDUSDT,IDOLUSDT,ILVUSDT,IMXUSDT,INUSDT,INITUSDT,INJUSDT,IOUSDT,IOSTUSDT,IOTAUSDT,IOTXUSDT,IPUSDT,IQUSDT,JASMYUSDT,JELLYJELLYUSDT,JOEUSDT,JSTUSDT,JTOUSDT,JUPUSDT,JUVUSDT,KAIUSDT,KAITOUSDT,KASUSDT,KAVAUSDT,KDAUSDT,KERNELUSDT,KMNOUSDT,KNCUSDT,KOMAUSDT,KSMUSDT,LAUSDT,LAYERUSDT,LAZIOUSDT,LDOUSDT,LINEAUSDT,LINKUSDT,LISTAUSDT,LPTUSDT,LQTYUSDT,LRCUSDT,LSKUSDT,LTCUSDT,LUMIAUSDT,LUNA2USDT,LUNCUSDT,MUSDT,MAGICUSDT,MANAUSDT,MANTAUSDT,MASKUSDT,MAVUSDT,MAVIAUSDT,MBLUSDT,MBOXUSDT,MEUSDT,MELANIAUSDT,MEMEUSDT,MEMEFIUSDT,MERLUSDT,METISUSDT,MEWUSDT,MILKUSDT,MINAUSDT,MITOUSDT,MKRUSDT,MLNUSDT,MOCAUSDT,MOODENGUSDT,MORPHOUSDT,MOVEUSDT,MOVRUSDT,MTLUSDT,MUBARAKUSDT,MYROUSDT,MYXUSDT,NAORISUSDT,NEARUSDT,NEIROUSDT,NEIROETHUSDT,NEOUSDT,NEWTUSDT,NEXOUSDT,NFPUSDT,NILUSDT,NKNUSDT,NMRUSDT,NOTUSDT,NTRNUSDT,NXPCUSDT,OBOLUSDT,OGUSDT,OGNUSDT,OLUSDT,OMUSDT,OMNIUSDT,ONDOUSDT,ONEUSDT,ONGUSDT,ONTUSDT,OPUSDT,OPENUSDT,ORBSUSDT,ORCAUSDT,ORDIUSDT,OSMOUSDT,OXTUSDT,PARTIUSDT,PAXGUSDT,PENDLEUSDT,PENGUUSDT,PEOPLEUSDT,PEPEUSDT,PERPUSDT,PHAUSDT,PHBUSDT,PIPPINUSDT,PIVXUSDT,PIXELUSDT,PLAYUSDT,PLUMEUSDT,PNUTUSDT,POLUSDT,POLYXUSDT,PONDUSDT,PONKEUSDT,POPCATUSDT,PORT3USDT,PORTALUSDT,PORTOUSDT,POWRUSDT,PROMUSDT,PROMPTUSDT,PROVEUSDT,PSGUSDT,PTBUSDT,PUFFERUSDT,PUMPUSDT,PUMPBTCUSDT,PUNDIXUSDT,PYRUSDT,PYTHUSDT,QUSDT,QUSDT,QKCUSDT,QNTUSDT,QTUMUSDT,QUICKUSDT,RAREUSDT,RAYSOLUSDT,RDNTUSDT,REDUSDT,REIUSDT,RENDERUSDT,REQUSDT,RESOLVUSDT,REZUSDT,RIFUSDT,RLCUSDT,RONINUSDT,ROSEUSDT,RPLUSDT,RSRUSDT,RUNEUSDT,RVNUSDT,SUSDT,SAFEUSDT,SAGAUSDT,SAHARAUSDT,SANDUSDT,SANTOSUSDT,SAPIENUSDT,SCRUSDT,SCRTUSDT,SEIUSDT,SFPUSDT,SHELLUSDT,SHIBUSDT,SIGNUSDT,SIRENUSDT,SKATEUSDT,SKLUSDT,SKYUSDT,SKYAIUSDT,SLERFUSDT,SLFUSDT,SNXUSDT,SOLUSDT,SOLVUSDT,SOMIUSDT,SONICUSDT,SOONUSDT,SOPHUSDT,SPELLUSDT,SPKUSDT,SPXUSDT,SQDUSDT,SSVUSDT,STEEMUSDT,STGUSDT,STOUSDT,STORJUSDT,STRKUSDT,STXUSDT,SUIUSDT,SUNUSDT,SUPERUSDT,SUSHUSDT,SWARMSUSDT,SWELLUSDT,SXPUSDT,SXTUSDT,SYNUSDT,SYRUPUSDT,SYSUSDT,TUSDT,TAUSDT,TACUSDT,TAGUSDT,TAIKOUSDT,TAKEUSDT,TANSSIUSDT,TAOUSDT,TFUELUSDT,THEUSDT,THETAUSDT,TIAUSDT,TKOUSDT,TLMUSDT,TNSRUSDT,TOKENUSDT,TONUSDT,TOWNSUSDT,TRBUSDT,TREEUSDT,TRUUSDT,TRUMPUSDT,TRXUSDT,TSTUSDT,TURBOUSDT,TUTUSDT,TWTUSDT,UMAUSDT,UNIUSDT,USD1USDT,USDCUSDT,USDEUSDT,USDTUSDT,USELESSUSDT,USTCUSDT,USUALUSDT,UTKUSDT,UXLINKUSDT,VANAUSDT,VANRYUSDT,VELODROMEUSDT,VELVETUSDT,VETUSDT,VICUSDT,VINEUSDT,VIRTUALUSDT,VOXELUSDT,VTHOUSDT,VVVUSDT,WUSDT,WALUSDT,WANUSDT,WAXPUSDT,WBETHUSDT,WBTCUSDT,WCTUSDT,WIFUSDT,WINUSDT,WLDUSDT,WLFIUSDT,WOOUSDT,XAIUSDT,XCNUSDT,XECUSDT,XLMUSDT,XNOUSDT,XNYUSDT,XPLUSDT,XRPUSDT,XTZUSDT,XUSDUSDT,XVGUSDT,XVSUSDT,YALAUSDT,YFIUSDT,YGGUSDT,ZECUSDT,ZENUSDT,ZEREBROUSDT,ZETAUSDT,ZILUSDT,ZKUSDT,ZKJUSDT,ZORAUSDT,ZRCUSDT,ZROUSDT,ZRXUSDT").split(",")
TF_LIST = os.getenv("TF_LIST", "5m,15m,30m,1h,4h").split(",")

# Количество результатов для каждого таймфрейма
RESULTS = {
    "5m": int(os.getenv("RESULTS_5m", "2000")),
    "15m": int(os.getenv("RESULTS_15m", "2000")),
    "30m": int(os.getenv("RESULTS_30m", "2000")),
    "1h": int(os.getenv("RESULTS_1h", "1500")),
    "4h": int(os.getenv("RESULTS_4h", "1000"))
}

# Настройки кэша и HTTP
CACHE_TTL_SECONDS = int(os.getenv("CACHE_TTL_SECONDS", "90"))
HTTP_TIMEOUT_SECONDS = int(os.getenv("HTTP_TIMEOUT_SECONDS", "20"))
MAX_RETRIES = int(os.getenv("MAX_RETRIES", "3"))
CONCURRENCY = int(os.getenv("CONCURRENCY", "4")) 

# OpenAI / LLM settings for cursor module
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
OPENAI_BASE_URL = os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1")
OPENAI_TIMEOUT_SECONDS = int(os.getenv("OPENAI_TIMEOUT_SECONDS", "60"))

# Telegram notifications (optional)
TELEGRAM_BOT_TOKEN = os.getenv("BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("BOT_CHAT_ID")